version: '2'
services:
  mysql:
    build: .
    platform: linux/amd64
    ports:
     - "3307:3306"
    volumes:
     - mysql_tls:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql_tls:
    driver: local

